### ISSUE TITLE
CHANGELOG.md not rendering

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/pub-dartlang-dart#73] opened 2017-02-14 08:59 UTC
For example in this library: https://pub.dartlang.org/packages/rxdart

clicking on CHANGELOG.md does nothing

**Comment by isoos** [comment] 2017-03-30 12:19
The root cause is: we have two `id="changelog"` elements: one is coming from the `README.md` (automatically generated based on the header text), the other is in the page template.

@mkustermann: this could be fixed by either not rendering the IDs in any user-provided markdown content, or by prefixing the template ids with something that is unlikely to come up in a normal situation.

Because github renders such markdown content with IDs (and it provides value), I think we should fix this by the second method.

**Closed** 2017-03-30 18:13 UTC
