### ISSUE TITLE
Search for "search" + recently updated returns an error.

### ISSUE THREAD

**Issue by derekdang** [dart-lang/pub-dartlang-dart#1635] opened 2018-09-20 06:24 UTC
Requested URL: https://pub.dartlang.org/flutter/packages?q=search&sort=updated
Request ID: 5753385c5c2c4e1c9bfb007b8cebe91c

**Comment by isoos** [comment] 2018-09-20 06:26
Thanks for filing it. Duplicate of https://github.com/dart-lang/pub-dartlang-dart/issues/1626, will be fixed once #1628 gets deployed (hopefully today).

**Closed by isoos** 2018-09-20 06:26 UTC
