### ISSUE TITLE
[analysis] Wrong analyzer version was used

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/pub-dartlang-dart#1010] opened 2018-02-21 18:45 UTC
URL: https://pub.dartlang.org/packages/rxdart#-analysis-tab-

I received a low health score, due to errors in the dart analyzer. However, it seems that an analyzer from Dart v2.0.0 dev20 was used, even though the pubspec is defined as following:

environment:
  sdk: '>=1.21.0 <2.0.0'

We do plan a v2 release eventually, but shouldn't this scoring tool use the proper SDK when compiling the result?

**Comment by isoos** [comment] 2018-02-21 20:54
Yeah, we feel your pain, but at the moment we have no plans to run analysis on 1.* SDKs. Unfortunately most packages use the same `sdk: '>=1.X.0 <2.0.0'`, and in itself it is no indication whether something is SDK-1.X-only.

The issue is duplicate of https://github.com/dart-lang/pub-dartlang-dart/issues/713, which has more context on the decision, closing this one.

**Closed by isoos** 2018-02-21 20:54 UTC
