### ISSUE TITLE
Awaiting analysis to complete taking a long time

### ISSUE THREAD

**Issue by felangel** [dart-lang/pub-dartlang-dart#2060] opened 2019-02-16 18:35 UTC
I've submitted updates to several packages over an hour ago and they are all still "Awaiting analysis to complete"

In addition, it's impossible to search for them. Is there some sort of maintenance which is causing all of this? Normally, everything is updated almost immediately after a submission.

See the following for an example:
https://pub.dartlang.org/packages/bloc
https://pub.dartlang.org/packages/flutter_bloc

**Comment by isoos** [comment] 2019-02-16 18:53
The log entries show that both packages were picked up and the analysis was completed, there were no indication of an error while we stored the analysis results. It looks like we have an issue with the caching, and the new results didn't show up on the page yet. In worst case, you should see the results in ~24 hours.

I'll address the caching issue next week, sorry for the inconvenience.

**Comment by felangel** [comment] 2019-02-16 18:55
Thanks for the quick reply! I was planning on pushing additional updates later today, do you think that would invalidate the cache?

**Comment by isoos** [comment] 2019-02-16 20:37
@felangel: it looks like your new version of `flutter_bloc` did get the cache updated for that version, but the `bloc` did not (yet). The search is connected with the analysis, and it is failing for the same reason (and another search-related one, see #2053 and #2057).

In general we don't recommend to publish a new version in the hope that it will "fix the site". It is very likely that you'll hit the same issue, and the new version won't fix everything by itself. A missing analysis is not a show-stopper for neither publishing, nor downloading packages, and we will do our best to fix it on regular work hours. Once the related code is fixed, the package will get re-analyzed and you'll see the scores.

**Comment by felangel** [comment] 2019-02-17 16:05
@isoos just another update:
Now all packages have a score but when I search for bloc (https://pub.dartlang.org/packages/bloc) it’s nowhere to be found.

When I search for angular bloc, bloc shows up 🤔

**Comment by isoos** [comment] 2019-02-17 16:09
@felangel: yes, search index missing the new analysis is known, and fix is done for that, but not deployed to production yet.

**Comment by felangel** [comment] 2019-02-17 22:18
@isoos looks like everything is back to normal 🎉. Would you like me to close this issue?

**Comment by isoos** [comment] 2019-02-18 07:24
@felangel let's keep this open until we fix the underlying causes, thanks!

**Comment by fadhly-permata** [comment] 2019-02-18 20:06
> 
> 
> @felangel: yes, search index missing the new analysis is known, and fix is done for that, but not deployed to production yet.

is this problem the same as what happened at #2068 ?

**Comment by isoos** [comment] 2019-02-18 20:30
Yes, it is the same root cause. The fix is already done, but it hasn't been deployed to prod yet.

**Comment by fadhly-permata** [comment] 2019-02-18 20:50
@isoos Thanks for your quick response dude.

**Comment by isoos** [comment] 2019-02-20 15:52
The fix is deployed to prod today, closing.

**Closed by isoos** 2019-02-20 15:52 UTC

**Comment by fadhly-permata** [comment] 2019-02-23 23:13
@isoos Thanks for reporting it dude 👍
