### ISSUE TITLE
Support marking a package stale/deprecated

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub-dartlang-dart#182] opened 2017-06-22 15:13 UTC
Need a way of marking a package stale/deprecated. For now we have to resort to README editing to make this clear, but would like a more explicit approach + special treatment for these in search, etc.

**Comment by kevmoo** [comment] 2017-08-18 00:04
We have a bigger conversation in a newer bug, so marking this one as

Duplicate of https://github.com/dart-lang/pub-dartlang-dart/issues/289

**Comment by kevmoo** [comment] 2017-08-18 00:05
Duplicates https://github.com/dart-lang/pub-dartlang-dart/issues/289

**Comment by kevmoo** [comment] 2017-08-18 00:05
Duplicate of #289

**Closed by kevmoo** 2017-08-18 00:04 UTC
Labels: Customer-Flutter
