### ISSUE TITLE
dart_to_js_rewriter should not be marked as Flutter

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub-dartlang-dart#963] opened 2018-02-05 21:37 UTC
URL: https://pub.dartlang.org/packages/dart_to_js_script_rewriter

This should be ONLY for web developers.

![screen shot 2018-02-05 at 1 36 56 pm](https://user-images.githubusercontent.com/5479/35830032-b0efc626-0a79-11e8-86fa-0e399e52ee6a.png)

**Comment by isoos** [comment] 2018-02-05 21:50
Duplicate of #598, hardcoded override is arriving in #960.

**Closed by isoos** 2018-02-05 21:50 UTC
Labels: Area: site feedback
