### ISSUE TITLE
keep a timeline view available

### ISSUE THREAD

**Issue by thumbert** [dart-lang/pub-dartlang-dart#723] opened 2017-12-05 16:14 UTC
URL: https://pub.dartlang.org/experimental

Current pub website shows the submissions ordered by time.  That makes it nice to check out what people contributed by looking at the top entries (I do this almost every day).  Often I discover an interesting package that I investigate further.  In the new website this "timeline" view is no longer available.  Please have a way to see the packages by submission time stamp too. 

Thanks!

**Comment by kevmoo** [comment] 2017-12-05 16:42
Duplicate of https://github.com/dart-lang/pub-dartlang-dart/issues/635

It's on our list!

**Closed by kevmoo** 2017-12-05 16:42 UTC
