### ISSUE TITLE
Rendering of some characters (e.g. >) in code blocks are wrong

### ISSUE THREAD

**Issue by sgjesse** [dart-lang/pub-dartlang-dart#16] opened 2015-05-22 13:21 UTC
E.g. look at https://pub.dartlang.org/packages/stagehand. Here

    $&gt; pub global activate stagehand

is shown instead of

    $> pub global activate stagehand

**Comment by mkustermann** [comment] 2015-07-10 08:58
Duplicate of #31

**Closed by mkustermann** 2015-07-10 08:58 UTC
Labels: duplicate, markdown-issue
