### ISSUE TITLE
Relative links are sometimes resolved incorrectly

### ISSUE THREAD

**Issue by mklim** [dart-lang/pub-dartlang-dart#2278] opened 2019-05-15 01:05 UTC
Seeing this in [in_app_purchase](https://pub.dev/packages/in_app_purchase), which uses relative links in its [README](https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/README.md). These are resolved correctly on Github. For example: `[example app README](example/README.md)` links to `https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/example/README.md`.

However on pub.dartlang.org, the relative root of the entire repo is used instead of the  package's inner location in order to construct the link. So the above link ends up missing the `packages/in_app_purchase` part of the URL and linking to a 404.

Causing flutter/flutter#32546. I think this issue has something to do with the pub package not living in the root of the repo. We may be missing a config option to fix this, but I couldn't find one. The `homepage` in `pubspec.yaml` is set to `https://github.com/flutter/plugins/tree/master/packages/in_app_purchase`. However the "Repository" link on pub does link back to the root of the entire repo instead. Not sure if that's related.

**Comment by isoos** [comment] 2019-05-15 06:12
Duplicate of #2018, keeping the older issue open.

**Closed by isoos** 2019-05-15 06:12 UTC
