### ISSUE TITLE
Feature: Group packages by unique name/project

### ISSUE THREAD

**Issue by supermuka** [dart-lang/pub-dartlang-dart#715] opened 2017-12-04 23:27 UTC
Just a suggest. I think that would be interesting agroup packages related into a unique group name/project. Could be easier to find all packages related and understand the purpose as a whole.

Example:

Group name/project: Shelf
Packages related: shelf, shelf_auth, shelf_route, etc.

Group name/project: Angular
Packages related: angular, angular_components, angular_form, etc.

**Comment by mit-mit** [comment] 2018-01-15 13:01
Closing as a duplicate of https://github.com/dart-lang/pub-dartlang-dart/issues/367

**Closed by mit-mit** 2018-01-15 13:01 UTC
