### ISSUE TITLE
Question (~feature request) - know if pub package is "flutter friendly"

### ISSUE THREAD

**Issue by mikemimik** [dart-lang/pub-dartlang-dart#61] opened 2016-11-16 04:42 UTC
As discussed in the flutter/flutter gitter channel this evening. I posed the question if flutter had an eco-system of packages yet. Pub.dartlang.org was the suggestion but was cautioned that only 'flutter friendly' packages would work with flutter. To which I responded with "How do you know which pub packages are flutter friendly."

Food for thought.

**Comment by mit-mit** [comment] 2016-12-06 15:03
Thanks, mikemimik, yes this is something we are considering

**Comment by mit-mit** [comment] 2016-12-06 15:04
Closing as a dupe of https://github.com/dart-lang/pub-dartlang-dart/issues/39

**Closed by mit-mit** 2016-12-06 15:04 UTC
Labels: enhancement
