### ISSUE TITLE
No plugins are detected.

### ISSUE THREAD

**Issue by JosephNK** [dart-lang/pub-dartlang-dart#2057] opened 2019-02-15 11:20 UTC
URL: https://pub.dartlang.org/packages?q=flutter_kakao_login => found
URL: https://pub.dartlang.org/flutter/packages?q=flutter_kakao_login => not found

The flutter_kakao_login plug-in will only search if the filter condition is set to ALL at https://pub.dartlang.org/flutter.
If the filter condition is FLUTTER, it is not searched.
Please let me know why.

**Comment by isoos** [comment] 2019-02-15 11:30
This has the same root cause as #2053, which will be addressed via #2055.

There are two additional info with the symptoms:
- the search index loaded only the version `0.0.6`, and not the `0.0.7`
- the loaded scorecard apparently did not have the `uses-flutter` flag.

**Comment by isoos** [comment] 2019-02-15 14:55
I'm starting to understand the root cause of not having the `uses-flutter` flag in the search index: at the time when the index tries to load the package document for the freshly uploaded version, there was no analysis yet, neither with that runtimeVersion, nor with any previous one.

There was no fallback to an earlier version, and a placeholder null-analysis was used, which didn't have the platform information. It was made worse by the underlying bug of #2055, which didn't trigger an update even after the analysis was done.

Instead of the placeholder null-analysis we'll need to just keep using the existing entry in the index, which should be the latest correct analysis result for a past version that was latest stable at that time.

**Comment by JosephNK** [comment] 2019-02-16 14:42
@isoos 

URL: https://pub.dartlang.org/packages?q=flutter_kakao_login => found
URL: https://pub.dartlang.org/flutter/packages?q=flutter_kakao_login => found

It works now.
Did your search issue resolve?
If it is resolved, you may close this issue.

**Comment by isoos** [comment] 2019-02-16 14:48
@JosephNK it was expected that it will be resolved automatically (after ~24-26 hours at most), but I'd keep this issue open because the underlying cause is not addressed yet.

**Comment by isoos** [comment] 2019-02-20 15:53
The fix was deployed to prod today, closing the issue.

**Closed by isoos** 2019-02-20 15:53 UTC
