### ISSUE TITLE
search results: 3 results found header, 2 results listed

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1921] opened 2019-01-08 17:31 UTC
URL: https://pub.dartlang.org/packages?q=aqueduct

![screen shot 2019-01-08 at 9 30 57 am](https://user-images.githubusercontent.com/17034/50848128-36c4d680-1328-11e9-9306-5f8bf820df09.png)

**Comment by isoos** [comment] 2019-01-10 08:30
Root cause: the prod search index has three results: `aqueduct`, `aqueduct_test` and `aqueduct_orm`, but the last one is removed in the post-filter stage: it seems to be that the package does not exists (or it was removed at one point).

Not sure why it is not removed from the index, it should not be there.

Staging index is OK.

**Comment by isoos** [comment] 2019-01-10 10:42
It seems that there was a single version of the package: #1193.

We are doing the snapshot removals wrong: we don't do existence check neither at the time of snapshot load, nor at the time of snapshot save. The existence check we do is working only for a narrow window of full-package removals, we could probably get rid of it.

I wouldn't add even a quick `Package` existence check at load time (to minimize the potential downtime), but we should definitely do it at save time. It is not an immediate fix, but cleans up the index eventually.

We should also use the search-service notifications to trigger a re-index, which should trigger an immediate delete from the index, but that is not reliable to reach all search indexes.

**Comment by jonasfj** [comment] 2019-01-10 12:15
We should probably regenerate the search index from scratch at some reasonable interval to ensure eventual consistency, filed #1932 -- I'm sure there are many ways we could do this.

**Comment by isoos** [comment] 2019-01-29 09:44
This is now fixed in staging, will be part of the next deploy.

**Closed by isoos** 2019-01-29 09:44 UTC
Labels: Area: site feedback
