### ISSUE TITLE
Search is not always working.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/pub-dartlang-dart#212] opened 2017-07-07 11:25 UTC
From Gitter:

Marcin Sydor @marcinsydor 13:02
Searching on pub.dartlang.org does not work well to me. Sometimes I can't find a package using key words. And even sometimes searching by package name not showing the package. e.g. https://pub.dartlang.org/search?q=node_interop. Should I report it somewhere or it know issue?

**Comment by mkustermann** [comment] 2017-07-07 11:28
A better search system is being actively developed at this moment. I think there are actually a few issues open already in this issue tracker, which track specific search related issues.

**Comment by isoos** [comment] 2017-07-07 11:29
This is a duplicate of https://github.com/dart-lang/pub-dartlang-dart/issues/189

**Comment by mkustermann** [comment] 2017-07-07 11:31
Let's close this one then.

**Closed by mkustermann** 2017-07-07 11:31 UTC
