### ISSUE TITLE
Add a download count besides the rating

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/pub-dartlang-dart#1561] opened 2018-08-29 08:33 UTC
Hi,

I know that this was discussed before and that a download count isn't a very accurate metric but:

1.  Even if automated build systems my lead to multiple downloads of the same user it signals that the package is heavily used in some project
2.  It's a real motivational factor for a package author to see how much his package is used which the rating cannot transport.
3.  I see no reason why it would hurt to show this metric ;-)

Cheers
Thomas

**Comment by isoos** [comment] 2018-09-19 14:28
Previous request: https://github.com/dart-lang/pub-dartlang-dart/issues/757

**Comment by escamoteur** [comment] 2018-09-19 20:17
@isoos  After discussion with @mit-mit this discussion is open again.

**Comment by mit-mit** [comment] 2018-09-21 12:19
Jonas to look into what data we gather today for this

**Comment by sortie** [comment] 2018-09-26 11:20
The data is coming from the dartlang_pub_logs.external_rollup table. The popularity data is fetched using a very large database query in dartty_package_query/bin/_shared.dart, which groups the data by week and flavor. The actual table entries contains the package, the client IP, whether the package was used directly / by dev dependency / through flutter, and whether the client was in a known environment (travis, etc.).

@kevmoo Can you tell us more about the backing database for package requests? dart_package_query is a google internal package right now, are there any risks in making it public or e.g. giving @isoos access?

The popularity data itself is uploaded as "votes", maybe not quite presentable as "download counts". I would guess that the pub site itself has access to the database and could itself do a query like the popularity data script.

**Comment by mrmcq2u** [comment] 2019-04-10 18:24
http://libraries.io  allows you to see how many projects are dependent on your dart package. e.g https://libraries.io/pub/http  , you can even drill down and see see usage by version e.g https://libraries.io/pub/http/usage

**Comment by escamoteur** [comment] 2019-05-03 09:42
@mrmcq2u Yes but it doesn't give me a feeling on how popular my project is, how many users it has which is an important metric for the motivation of a maintainer.

**Comment by kevmoo** [comment] 2019-05-03 13:00
Duplicate of https://github.com/dart-lang/pub-dartlang-dart/issues/757

**Closed by kevmoo** 2019-05-03 13:00 UTC
Labels: Type: enhancement

**Comment by mrmcq2u** [comment] 2019-05-03 19:20
@escamoteur I think the problem with download counts is explained fairly well in #757, I think if you want a more thorough idea of how many people are using your package the best bet is seeing how many packages depend on it. It's not perfect but I can't think of a better solution myself :(

**Comment by escamoteur** [comment] 2019-05-07 13:44
@mrmcq2u Looking at the number of other packages that use your package does not help if you package is typically used be apps and not be public packages

**Comment by davidwparker** [comment] 2020-04-23 17:23
@kevmoo - wonder why you closed this and marked as duplicate of an already closed one?

The answer provided by @isoos in the other thread is unacceptable (blaming CI).
Raw counts are used in Ruby, PHP, Rust, etc. Not sure what the harm is in providing the data.

**Comment by kevmoo** [comment] 2020-04-23 17:31
@davidwparker that's the original issue + discussion + justification. We'd like to avoid covering the same topic many times.

**Comment by mit-mit** [comment] 2020-04-24 12:48
We've reconsidered this, and are looking into options for supporting this. The current tracking issue is https://github.com/dart-lang/pub-dev/issues/2714.
