### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by crazecoder** [dart-lang/pub-dartlang-dart#1507] opened 2018-08-09 06:17 UTC
URL: https://pub.dartlang.org/packages/open_file#-readme-tab-

<Describe your issue or suggestion here>

depends on open_file ^1.0.7 which doesn't match any versions, version solving failed.
the 1.0.5 is success

**Comment by isoos** [comment] 2018-08-09 14:34
duplicate of https://github.com/dart-lang/pub/issues/1965, and I think this is a pub client issue. @crazecoder: I'd suggest to include a full log of what is happening (`pub get -v`) on the other issue.

**Closed by isoos** 2018-08-09 14:34 UTC
