### ISSUE TITLE
[Feature Request] Expose what platforms a Flutter package supports.

### ISSUE THREAD

**Issue by dnfield** [dart-lang/pub-dartlang-dart#2098] opened 2019-02-28 20:19 UTC
Today, there's no way to easily tell what platform(s) a Flutter plugin supports.  Some support only one, some support multiple.  This will become more of a challenge for users as Flutter grows to support more Desktop/web/??? platforms.  

As a user, I would like to know what platform implementations are available in a package tagged "Flutter".

**Comment by jonasfj** [comment] 2019-02-28 22:31
@dnfield, can you deduce this based on automatic analysis? and if so, how would we do this?

**Comment by dnfield** [comment] 2019-02-28 22:41
I don't think this can be done automatically, but it could probably be done via a `pubspec.yaml` entry for supported platforms or something like that.

**Comment by jonasfj** [comment] 2019-03-04 11:47
It would be nice if packages could be tagged and categorized..

It's not obvious to me that what should look like, but we should explore it at some point :)

**Comment by sigurdm** [comment] 2019-03-04 13:09
Can a Flutter plugin be compiled/used on one platform if it doesn't have the other of the ios/android folders? Then we could auto-detect the presence of these (and the one for web-support, not sure what it's called) and present that in the pub interface.

That would require the user to remove the unsupported platform from the template.

**Comment by dnfield** [comment] 2019-03-04 14:52
@sigurdm I wouldn't rely on that.  A plug-in may have a regular dart implementation for one or more platforms but require other code for another. Or it might stub out the implentation for a platform in the iOS folder that doesn't actually do anything.

**Comment by sigurdm** [comment] 2019-03-05 09:02
Good points.
...So annotating is probably the way to go

**Comment by isoos** [comment] 2019-03-12 15:58
Previous discussion: https://github.com/dart-lang/pub-dartlang-dart/issues/144
Open issue in Flutter: https://github.com/flutter/flutter/issues/10288

I'd rather close this issue and keep only #144. Shall we copy some of the comment into #144?

**Comment by dnfield** [comment] 2019-03-12 16:19
That works for me!

**Comment by kevmoo** [comment] 2019-03-12 17:14
Duplicate of #144

**Closed by kevmoo** 2019-03-12 17:14 UTC
Labels: Type: enhancement
