### ISSUE TITLE
Pub build command failing in CI

### ISSUE THREAD

**Issue by unibeck** [dart-lang/pub-dartlang-dart#336] opened 2017-09-06 13:50 UTC
I have a angular dart app where `pub build` works fine locally, but on a `gitlab runner` running docker in docker (dind) I get the following error:

`Connection failed (OS Error: Network is unreachable, errno = 101), address = pub.dartlang.org, port = 443`
Here's the full pub build output https://gist.github.com/unibeck/64fcb55ba8cb3b25037847a5c4a2d8cb
It's interesting to note that I've reran the job a few times and got the same error but with a different address such as `address = pub.dartlang.org` or `address = storage.googleapis.com`

The last job that didn't have this problem occurred at 9/5/17 5:14 PM ET
The first job that had this problem occurred at 9/5/17 9:12 PM ET
The latest job that had this problem occurred at 9/6/17 8:51 AM ET

The docker image I'm using is custom built off docker-alpine with jdk8, gradle3.4, and dart1.24.2 installed. Let me know if there's any more information I could provide about my CI setup.

**Comment by mkustermann** [comment] 2017-09-06 14:21
This kind of error message occurs if the pub client cannot establish a tcp connection to the server. The issue ist almost certainly on the client side.

If you can somehow log into your docker container, you might be able to diagnose the issue by probing connectivity to the network. It might have also something todo with your `gitlab runner` hosting service.

Closing this issue, since it seems not related to our server.

**Closed by mkustermann** 2017-09-06 14:21 UTC
