### ISSUE TITLE
[team review] Shortly explain Popularity and Maintenance

### ISSUE THREAD

**Issue by filiph** [dart-lang/pub-dartlang-dart#629] opened 2017-11-22 23:27 UTC
Example page: https://pub.dartlang.org/experimental/packages/jsonp#-analysis-tab-

* Shortly explaining Popularity and Maintenance would go a long way. Just a single paragraph that shows up in every Analysis tab that says what type of things we're looking at. 
* Or put it in suggestions, such as "Increase popularity of your package by being more active in the community. Popularity is measured by the number of foos in your bars.".

**Comment by kevmoo** [comment] 2017-11-22 23:44
Duplicate of https://github.com/dart-lang/pub-dartlang-dart/issues/596

**Comment by kevmoo** [comment] 2017-11-22 23:44
@filiph – please add other details to the existing bug

**Closed by kevmoo** 2017-11-22 23:44 UTC
Labels: v2 Design
