### ISSUE TITLE
HTTP 500 relating to search

### ISSUE THREAD

**Issue by sortie** [dart-lang/pub-dartlang-dart#1741] opened 2018-11-01 10:43 UTC
At 03:29:11 CET, an user saw a 500 when searching:

```
pub.utils: HTTP GET https://search-dot-dartlang-pub.appspot.com/search?q=lightning&offset=0&limit=10
pub: Request handler failed

Error:
    Exception: Service returned status code 502
Stack:
    package:pub_dartlang_org/shared/search_client.dart 47:7       SearchClient.search
    package:pub_dartlang_org/frontend/handlers.dart 781:33        _apiSearchHandler
    package:pub_dartlang_org/frontend/handlers.dart 80:25         appHandler
    bin/service/frontend.dart 59:36                               _main.<fn>.<fn>
```

And then 8 other customers saw such a HTTP error up until 03:30:13 CET.

At 03:31:40 CET, these two warnings happened on the search instances:

```Could not connect to memcache instance at 35.190.255.1:11211
MemcacheError(status: Status(ERROR), message: Error storing item)
```
```
Could not connect to memcache instance at localhost:11211
NetworkError: "SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 34212"
```

After which no more 500 errors happened for customers.

Unclear what happened here. Did the memcache break and search didn't handle that gracefully? Or since the front end saw HTTP 502, could it be that the search instance became unreachable?

**Comment by isoos** [comment] 2018-11-05 08:40
`502` seems to be the error we get when there is a connectivity issue somewhere outside of the scope of our app. We didn't have any request-related exception, and the actual request is serving right now.

The two searches closes to the time window (`2018-11-01 03:28:36.918 CET`, `2018-11-01 03:30:00.944 CET`) were both successful, and I don't see anything out of the ordinary in the log entries. I think this was a network issue.

**Comment by sortie** [comment] 2018-11-08 20:49
This did happen again yesterday FWIW.

**Comment by isoos** [comment] 2018-12-06 08:19
This is a duplicate of #1831 (which has the investigation and resolution info), closing this one.

**Closed by isoos** 2018-12-06 08:19 UTC
