### ISSUE TITLE
please mark this is discontinued: analyzer_cli

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub-dartlang-dart#1443] opened 2018-07-11 20:23 UTC
URL: https://pub.dartlang.org/packages/analyzer_cli

CC @devoncarew

**Comment by sortie** [comment] 2018-07-12 08:59
Duplicate of #1399.

This has already been done. Due to a bug in pub, the package page was not regenerated after it was marked as discontinued. It will be fixed in the next deployment (tentatively today), which also should contain a fix, so newly discontinued packages don't have to wait for the next deployment.

**Closed by sortie** 2018-07-12 08:59 UTC
Labels: Area: discontinue request, Area: site feedback
